server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        max-header-size: 30MB
      routes:
        - id: auth-server
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**, /oauth2/**, /login/**
        
        - id: bff-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/**

        - id: storage-service
          uri: http://localhost:8083
          predicates:
            - Path=/storage/**

        - id: workflow-service
          uri: http://localhost:8084
          predicates:
            - Path=/workflow/**

        - id: document-service
          uri: http://localhost:8086
          predicates:
            - Path=/document/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

