server:
  port: 8082
  servlet:
    session:
      cookie:
        name: BFFSESSIONID
        http-only: true
        secure: false
        path: /
        max-age: 86400
  forward-headers-strategy: framework

spring:
  application:
    name: bff-service
  security:
    oauth2:
      client:
        registration:
          bff-client:
            provider: spring
            client-id: bff-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
            scope: openid, profile, email, offline_access
            client-name: BFF Client
        provider:
          spring:
            issuer-uri: http://localhost:9000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB



app:
  apis:
    workflow: 'http://localhost:8084'
    storage: 'http://localhost:8083'
    document: 'http://localhost:8086'
logging:
  level:
    org.springframework.security: DEBUG